### ISSUE TITLE
General | Navbar: links on hover

### ISSUE THREAD

**Issue by loogart** [loogart/lapoutineweek#16]
Navbar: remove underline on hover link

<img width="1122" alt="Screen Shot 2020-01-25 at 12 04 49 PM" src="https://user-images.githubusercontent.com/7881400/73124573-f653ed00-3f6a-11ea-8d06-5c63860bd861.png">
<img width="1172" alt="Screen Shot 2020-01-25 at 12 04 44 PM" src="https://user-images.githubusercontent.com/7881400/73124574-f653ed00-3f6a-11ea-89d6-54482a587cac.png">

**Comment by matbalazsi** [comment]
not reproduced on staging. Review on live when published
