### ISSUE TITLE
Results | Saputo Red banner

### ISSUE THREAD

**Issue by loogart** [loogart/lapoutineweek#17]
1. implement inside the .icard element
2. add to the quick preview modal as well (right above the .modal-body element)

**icard element**
```
<a href="#!" data-toggle="modal" data-target="#previewProduct">
  <div class="icard">
 <img src="../img/photos/poutine1.jpg" alt="" class="icard-img">
<div class="icard-content">
<h3>Restaurant Name</h3>
<h4>Poutine Name</h4>
<p class="d-none d-md-block">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus iste, amet non itaque repellendus animi dolor nemo cupiditate aperiam.</p>
<div class="icard-footer">
<p class="price">$16</p>
<p class="distance">2.1&nbsp;km</p>
</div>
 </div>
<div class="red-banner">
<img src="../img/logo-saputo-white.svg" alt="saputo logo">&nbsp;<span class="d-none d-sm-inline-block">Made with Saputo Cheese</span>
 </div>
</div>
</a>
```

<img width="1440" alt="Screen Shot 2020-01-25 at 12 06 48 PM" src="https://user-images.githubusercontent.com/7881400/73124619-4fbc1c00-3f6b-11ea-8c8c-2906761b0c7f.png">

**quick preview modal**
```
<div class="red-banner red-banner__quick-preview">
    <img src="../img/logo-saputo-white.svg" alt="saputo logo">&nbsp;<span class="d-none d-sm-inline-block">Made with Saputo Cheese</span>
</div>
```
<img width="1440" alt="Screen Shot 2020-01-25 at 12 10 09 PM" src="https://user-images.githubusercontent.com/7881400/73124645-a32e6a00-3f6b-11ea-8d8e-c1bf0765e10f.png">

**Comment by matbalazsi** [comment]
<img width="199" alt="Screen Shot 2020-01-27 at 9 29 32 PM" src="https://user-images.githubusercontent.com/11080515/73233483-b2bcd700-4154-11ea-914a-be5b82b90f12.png">

I noticed an issue on mobile, where the white "Made with Saputo Cheese" overlays the restaurant name

**Comment by loogart** [comment]
> <img alt="Screen Shot 2020-01-27 at 9 29 32 PM" width="199" src="https://user-images.githubusercontent.com/11080515/73233483-b2bcd700-4154-11ea-914a-be5b82b90f12.png">
> 
> I noticed an issue on mobile, where the white "Made with Saputo Cheese" overlays the restaurant name

@matbalazsi thanks man! here is the fix: update the `.d-sm-inline-block` class to `d-md-inline-block`

```
<div class="red-banner">
     <img src="../img/logo-saputo-white.svg" alt="saputo logo">
     &nbsp;<span class="d-none d-md-inline-block">Made with Saputo Cheese</span>
</div>
```

**Comment by matbalazsi** [comment]
What about the products page?
