### ISSUE TITLE
General | Search: Search Button

### ISSUE THREAD

**Issue by loogart** [loogart/lapoutineweek#29]
When you hit the search button, it should reload the page with the restaurant names closest to the typed content by the user.

**Comment by matbalazsi** [comment]
There are many possibilities here:
   -Is the issue that the page does not load? We do not access the results page if no restaurants were found
   -Is the issue with the results order (names closest typed by the user)? Ordering by text similarity is an advanced feature. It may not be realistic to implement before the 1rst

**Comment by loogart** [comment]
@matbalazsi I think it was the Capital letters - i was typing all lower case. Otherwise it works very well! Can we search words regardless of letter capitalization?
