### ISSUE TITLE
Results | Mobile filters map view

### ISSUE THREAD

**Issue by loogart** [loogart/lapoutineweek#34]
Mobile filters don't show up. Might need to remove filters on mobile map or figure another way...
UI to work on first, then implementation.

![Screen Shot 2020-01-28 at 9 06 43 PM](https://user-images.githubusercontent.com/7881400/73322021-19ec9100-4212-11ea-9255-b39f4c4984a6.png)

**Comment by loogart** [comment]
@matbalazsi can we simply remove the filters button on mobile map view?

**Comment by matbalazsi** [comment]
I've worked on a solution. They will appear on the mpa now. Let me know what you think on next release
