### ISSUE TITLE
Navbar city selector and language 

### ISSUE THREAD

**Issue by loogart** [loogart/lapoutineweek#5]

**Comment by matbalazsi** [comment]
Fixed except for very specific widths for administrators (they have more options in the nav)

**Comment by loogart** [comment]
@matbalazsi the navbar reverted back to the old weird stacked look
<img width="493" alt="screen shot 2019-01-31 at 7 14 30 am" src="https://user-images.githubusercontent.com/7881400/52053658-f40dad00-2527-11e9-9629-3f03cdeab22b.png">
