### ISSUE TITLE
RESULTS: Search bar

### ISSUE THREAD

**Issue by loogart** [loogart/lapoutineweek#51]
- [ ] When user clicks down arrow, they can navigate to the items shown under the search bar and hit ENTER to filter
- [ ] Search results don't show up all the time (see screenshot below when I type "Paulo"
- [x] styling of list items should match prototype

<img width="1508" alt="Screen Shot 2021-01-24 at 10 26 27 PM" src="https://user-images.githubusercontent.com/7881400/105657804-378b1f80-5e93-11eb-94e7-bb89f387e53c.png">

<img width="1508" alt="Screen Shot 2021-01-24 at 10 27 59 PM" src="https://user-images.githubusercontent.com/7881400/105657925-6ef9cc00-5e93-11eb-96ce-fe2acd00927e.png">

<img width="1508" alt="Screen Shot 2021-01-24 at 10 29 20 PM" src="https://user-images.githubusercontent.com/7881400/105658012-9ea8d400-5e93-11eb-9947-a099370971d0.png">

**Comment by matbalazsi** [comment]
Updating style. 
The functionality of arrow up / arrow down is a big change. Will try to fix before the festival
